CREATE OR REPLACE VIEW v_confused_activities_no_transfer AS

SELECT SUM(count) AS count, features, col
FROM (
SELECT sum_dishes_x_microwave AS count, features, 'dishes_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_coffee AS count, features, 'dishes_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_null AS count, features, 'dishes_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_faucet AS count, features, 'dishes_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_kettle AS count, features, 'dishes_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_chopping_food AS count, features, 'dishes_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_conversation AS count, features, 'dishes_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_eating_popcorn AS count, features, 'dishes_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_making_popcorn_in_microwave AS count, features, 'dishes_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_dishes_x_phone_vibrating AS count, features, 'dishes_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_dishes AS count, features, 'microwave_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_coffee AS count, features, 'microwave_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_null AS count, features, 'microwave_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_faucet AS count, features, 'microwave_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_kettle AS count, features, 'microwave_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_chopping_food AS count, features, 'microwave_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_conversation AS count, features, 'microwave_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_eating_popcorn AS count, features, 'microwave_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_making_popcorn_in_microwave AS count, features, 'microwave_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_microwave_x_phone_vibrating AS count, features, 'microwave_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_dishes AS count, features, 'coffee_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_microwave AS count, features, 'coffee_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_null AS count, features, 'coffee_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_faucet AS count, features, 'coffee_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_kettle AS count, features, 'coffee_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_chopping_food AS count, features, 'coffee_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_conversation AS count, features, 'coffee_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_eating_popcorn AS count, features, 'coffee_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_making_popcorn_in_microwave AS count, features, 'coffee_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_coffee_x_phone_vibrating AS count, features, 'coffee_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_dishes AS count, features, 'null_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_microwave AS count, features, 'null_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_coffee AS count, features, 'null_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_faucet AS count, features, 'null_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_kettle AS count, features, 'null_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_chopping_food AS count, features, 'null_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_conversation AS count, features, 'null_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_eating_popcorn AS count, features, 'null_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_making_popcorn_in_microwave AS count, features, 'null_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_null_x_phone_vibrating AS count, features, 'null_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_dishes AS count, features, 'faucet_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_microwave AS count, features, 'faucet_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_coffee AS count, features, 'faucet_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_null AS count, features, 'faucet_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_kettle AS count, features, 'faucet_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_chopping_food AS count, features, 'faucet_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_conversation AS count, features, 'faucet_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_eating_popcorn AS count, features, 'faucet_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_making_popcorn_in_microwave AS count, features, 'faucet_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_faucet_x_phone_vibrating AS count, features, 'faucet_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_dishes AS count, features, 'kettle_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_microwave AS count, features, 'kettle_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_coffee AS count, features, 'kettle_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_null AS count, features, 'kettle_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_faucet AS count, features, 'kettle_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_chopping_food AS count, features, 'kettle_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_conversation AS count, features, 'kettle_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_eating_popcorn AS count, features, 'kettle_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_making_popcorn_in_microwave AS count, features, 'kettle_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_kettle_x_phone_vibrating AS count, features, 'kettle_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_dishes AS count, features, 'chopping_food_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_microwave AS count, features, 'chopping_food_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_coffee AS count, features, 'chopping_food_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_null AS count, features, 'chopping_food_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_faucet AS count, features, 'chopping_food_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_kettle AS count, features, 'chopping_food_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_conversation AS count, features, 'chopping_food_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_eating_popcorn AS count, features, 'chopping_food_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_making_popcorn_in_microwave AS count, features, 'chopping_food_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_chopping_food_x_phone_vibrating AS count, features, 'chopping_food_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_dishes AS count, features, 'conversation_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_microwave AS count, features, 'conversation_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_coffee AS count, features, 'conversation_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_null AS count, features, 'conversation_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_faucet AS count, features, 'conversation_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_kettle AS count, features, 'conversation_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_chopping_food AS count, features, 'conversation_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_eating_popcorn AS count, features, 'conversation_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_making_popcorn_in_microwave AS count, features, 'conversation_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_conversation_x_phone_vibrating AS count, features, 'conversation_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_dishes AS count, features, 'eating_popcorn_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_microwave AS count, features, 'eating_popcorn_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_coffee AS count, features, 'eating_popcorn_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_null AS count, features, 'eating_popcorn_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_faucet AS count, features, 'eating_popcorn_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_kettle AS count, features, 'eating_popcorn_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_chopping_food AS count, features, 'eating_popcorn_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_conversation AS count, features, 'eating_popcorn_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_making_popcorn_in_microwave AS count, features, 'eating_popcorn_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_eating_popcorn_x_phone_vibrating AS count, features, 'eating_popcorn_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_dishes AS count, features, 'making_popcorn_in_microwave_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_microwave AS count, features, 'making_popcorn_in_microwave_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_coffee AS count, features, 'making_popcorn_in_microwave_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_null AS count, features, 'making_popcorn_in_microwave_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_faucet AS count, features, 'making_popcorn_in_microwave_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_kettle AS count, features, 'making_popcorn_in_microwave_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_chopping_food AS count, features, 'making_popcorn_in_microwave_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_conversation AS count, features, 'making_popcorn_in_microwave_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_eating_popcorn AS count, features, 'making_popcorn_in_microwave_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_making_popcorn_in_microwave_x_phone_vibrating AS count, features, 'making_popcorn_in_microwave_x_phone_vibrating' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_dishes AS count, features, 'phone_vibrating_x_dishes' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_microwave AS count, features, 'phone_vibrating_x_microwave' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_coffee AS count, features, 'phone_vibrating_x_coffee' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_null AS count, features, 'phone_vibrating_x_null' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_faucet AS count, features, 'phone_vibrating_x_faucet' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_kettle AS count, features, 'phone_vibrating_x_kettle' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_chopping_food AS count, features, 'phone_vibrating_x_chopping_food' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_conversation AS count, features, 'phone_vibrating_x_conversation' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_eating_popcorn AS count, features, 'phone_vibrating_x_eating_popcorn' AS col FROM v_results_no_transfer_aggr UNION
SELECT sum_phone_vibrating_x_making_popcorn_in_microwave AS count, features, 'phone_vibrating_x_making_popcorn_in_microwave' AS col FROM v_results_no_transfer_aggr
) t GROUP BY features, col ORDER BY count DESC
