CREATE MATERIALIZED VIEW v_feature_testing_transfers AS
SELECT
t.source_device AS source_device_id,
t.target_device AS target_device_id,
t.source_dataset AS source_dataset_id,
t.target_dataset AS target_dataset_id,
source_devices.name AS source_device,
source_devices.type AS source_device_type,
target_devices.name AS target_device,
target_devices.type AS target_device_type,
features.name AS sensor_stream,
source_datasets.name AS source_dataset,
source_datasets.room AS source_room,
target_datasets.name AS target_dataset,
target_datasets.room AS target_room,
source_locations.name AS source_location,
target_locations.name AS target_location,
scaled_independently,
feature,
accuracy

FROM
(
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'abs_energy' AS feature FROM results_feature_testing WHERE "abs_energy" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'absolute_sum_of_changes' AS feature FROM results_feature_testing WHERE "absolute_sum_of_changes" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'approximate_entropy__m_2__r_0.1' AS feature FROM results_feature_testing WHERE "approximate_entropy__m_2__r_0.1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'approximate_entropy__m_2__r_0.3' AS feature FROM results_feature_testing WHERE "approximate_entropy__m_2__r_0.3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'approximate_entropy__m_2__r_0.5' AS feature FROM results_feature_testing WHERE "approximate_entropy__m_2__r_0.5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'approximate_entropy__m_2__r_0.7' AS feature FROM results_feature_testing WHERE "approximate_entropy__m_2__r_0.7" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'approximate_entropy__m_2__r_0.9' AS feature FROM results_feature_testing WHERE "approximate_entropy__m_2__r_0.9" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'ar_coefficient__k_10__coeff_0' AS feature FROM results_feature_testing WHERE "ar_coefficient__k_10__coeff_0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'ar_coefficient__k_10__coeff_1' AS feature FROM results_feature_testing WHERE "ar_coefficient__k_10__coeff_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'ar_coefficient__k_10__coeff_2' AS feature FROM results_feature_testing WHERE "ar_coefficient__k_10__coeff_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'ar_coefficient__k_10__coeff_3' AS feature FROM results_feature_testing WHERE "ar_coefficient__k_10__coeff_3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'ar_coefficient__k_10__coeff_4' AS feature FROM results_feature_testing WHERE "ar_coefficient__k_10__coeff_4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'augmented_dickey_fuller' AS feature FROM results_feature_testing WHERE "augmented_dickey_fuller" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_0' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_1' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_2' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_3' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_4' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_5' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_6' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_7' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_7" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_8' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'autocorrelation__lag_9' AS feature FROM results_feature_testing WHERE "autocorrelation__lag_9" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'binned_entropy__max_bins_10' AS feature FROM results_feature_testing WHERE "binned_entropy__max_bins_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'count_above_mean' AS feature FROM results_feature_testing WHERE "count_above_mean" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'count_below_mean' AS feature FROM results_feature_testing WHERE "count_below_mean" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_0__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_0__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_0__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_0__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_0__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_0__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_0__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_0__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_10__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_10__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_10__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_10__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_10__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_10__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_10__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_10__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_11__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_11__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_11__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_11__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_11__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_11__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_11__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_11__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_12__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_12__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_12__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_12__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_12__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_12__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_12__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_12__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_14__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_14__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_14__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_14__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_14__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_14__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_14__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_14__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_1__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_1__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_1__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_1__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_1__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_1__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_1__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_1__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_2__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_2__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_2__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_2__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_2__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_2__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_2__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_2__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_4__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_4__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_4__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_4__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_4__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_4__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_4__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_4__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_5__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_5__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_5__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_5__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_5__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_5__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_5__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_5__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_6__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_6__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_6__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_6__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_6__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_6__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_6__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_6__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_7__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_7__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_7__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_7__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_7__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_7__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_7__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_7__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_8__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_8__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_8__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_8__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_8__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_8__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_8__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_8__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_9__w_10' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_9__w_10" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_9__w_2' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_9__w_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_9__w_20' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_9__w_20" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'cwt_coefficients__widths_(2, 5, 10, 20)__coeff_9__w_5' AS feature FROM results_feature_testing WHERE "cwt_coefficients__widths_(2, 5, 10, 20)__coeff_9__w_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_0' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_1' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_2' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_3' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_4' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_5' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_6' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_7' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_7" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_8' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'fft_coefficient__coeff_9' AS feature FROM results_feature_testing WHERE "fft_coefficient__coeff_9" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'first_location_of_maximum' AS feature FROM results_feature_testing WHERE "first_location_of_maximum" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'first_location_of_minimum' AS feature FROM results_feature_testing WHERE "first_location_of_minimum" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'friedrich_coefficients__m_3__r_30__coeff_0' AS feature FROM results_feature_testing WHERE "friedrich_coefficients__m_3__r_30__coeff_0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'friedrich_coefficients__m_3__r_30__coeff_1' AS feature FROM results_feature_testing WHERE "friedrich_coefficients__m_3__r_30__coeff_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'friedrich_coefficients__m_3__r_30__coeff_2' AS feature FROM results_feature_testing WHERE "friedrich_coefficients__m_3__r_30__coeff_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'friedrich_coefficients__m_3__r_30__coeff_3' AS feature FROM results_feature_testing WHERE "friedrich_coefficients__m_3__r_30__coeff_3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'has_duplicate' AS feature FROM results_feature_testing WHERE "has_duplicate" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'has_duplicate_max' AS feature FROM results_feature_testing WHERE "has_duplicate_max" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'has_duplicate_min' AS feature FROM results_feature_testing WHERE "has_duplicate_min" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'index_mass_quantile__q_0.1' AS feature FROM results_feature_testing WHERE "index_mass_quantile__q_0.1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'index_mass_quantile__q_0.2' AS feature FROM results_feature_testing WHERE "index_mass_quantile__q_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'index_mass_quantile__q_0.3' AS feature FROM results_feature_testing WHERE "index_mass_quantile__q_0.3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'index_mass_quantile__q_0.4' AS feature FROM results_feature_testing WHERE "index_mass_quantile__q_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'index_mass_quantile__q_0.6' AS feature FROM results_feature_testing WHERE "index_mass_quantile__q_0.6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'index_mass_quantile__q_0.7' AS feature FROM results_feature_testing WHERE "index_mass_quantile__q_0.7" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'index_mass_quantile__q_0.8' AS feature FROM results_feature_testing WHERE "index_mass_quantile__q_0.8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'index_mass_quantile__q_0.9' AS feature FROM results_feature_testing WHERE "index_mass_quantile__q_0.9" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'kurtosis' AS feature FROM results_feature_testing WHERE "kurtosis" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_number_of_peaks__n_1' AS feature FROM results_feature_testing WHERE "large_number_of_peaks__n_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_number_of_peaks__n_3' AS feature FROM results_feature_testing WHERE "large_number_of_peaks__n_3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_number_of_peaks__n_5' AS feature FROM results_feature_testing WHERE "large_number_of_peaks__n_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.0' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.05' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.05" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.1' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.15000000000000002' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.15000000000000002" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.2' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.25' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.25" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.30000000000000004' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.30000000000000004" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.35000000000000003' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.35000000000000003" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.4' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'large_standard_deviation__r_0.45' AS feature FROM results_feature_testing WHERE "large_standard_deviation__r_0.45" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'last_location_of_maximum' AS feature FROM results_feature_testing WHERE "last_location_of_maximum" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'last_location_of_minimum' AS feature FROM results_feature_testing WHERE "last_location_of_minimum" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'length' AS feature FROM results_feature_testing WHERE "length" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'longest_strike_above_mean' AS feature FROM results_feature_testing WHERE "longest_strike_above_mean" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'longest_strike_below_mean' AS feature FROM results_feature_testing WHERE "longest_strike_below_mean" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'max_langevin_fixed_point__m_3__r_30' AS feature FROM results_feature_testing WHERE "max_langevin_fixed_point__m_3__r_30" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'maximum' AS feature FROM results_feature_testing WHERE "maximum" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean' AS feature FROM results_feature_testing WHERE "mean" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change' AS feature FROM results_feature_testing WHERE "mean_abs_change" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.2__ql_0.0' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.2__ql_0.0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.2__ql_0.2' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.2__ql_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.2__ql_0.4' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.2__ql_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.2__ql_0.6' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.2__ql_0.6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.2__ql_0.8' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.2__ql_0.8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.4__ql_0.0' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.4__ql_0.0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.4__ql_0.2' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.4__ql_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.4__ql_0.4' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.4__ql_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.4__ql_0.6' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.4__ql_0.6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.4__ql_0.8' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.4__ql_0.8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.6__ql_0.0' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.6__ql_0.0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.6__ql_0.2' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.6__ql_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.6__ql_0.4' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.6__ql_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.6__ql_0.6' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.6__ql_0.6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.6__ql_0.8' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.6__ql_0.8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.8__ql_0.0' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.8__ql_0.0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.8__ql_0.2' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.8__ql_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.8__ql_0.4' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.8__ql_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.8__ql_0.6' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.8__ql_0.6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_0.8__ql_0.8' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_0.8__ql_0.8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_1.0__ql_0.0' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_1.0__ql_0.0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_1.0__ql_0.2' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_1.0__ql_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_1.0__ql_0.4' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_1.0__ql_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_1.0__ql_0.6' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_1.0__ql_0.6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_abs_change_quantiles__qh_1.0__ql_0.8' AS feature FROM results_feature_testing WHERE "mean_abs_change_quantiles__qh_1.0__ql_0.8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_autocorrelation' AS feature FROM results_feature_testing WHERE "mean_autocorrelation" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_change' AS feature FROM results_feature_testing WHERE "mean_change" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'mean_second_derivate_central' AS feature FROM results_feature_testing WHERE "mean_second_derivate_central" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'median' AS feature FROM results_feature_testing WHERE "median" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'minimum' AS feature FROM results_feature_testing WHERE "minimum" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'number_cwt_peaks__n_1' AS feature FROM results_feature_testing WHERE "number_cwt_peaks__n_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'number_cwt_peaks__n_5' AS feature FROM results_feature_testing WHERE "number_cwt_peaks__n_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'number_peaks__n_1' AS feature FROM results_feature_testing WHERE "number_peaks__n_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'number_peaks__n_3' AS feature FROM results_feature_testing WHERE "number_peaks__n_3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'number_peaks__n_5' AS feature FROM results_feature_testing WHERE "number_peaks__n_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'percentage_of_reoccurring_datapoints_to_all_datapoints' AS feature FROM results_feature_testing WHERE "percentage_of_reoccurring_datapoints_to_all_datapoints" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'percentage_of_reoccurring_values_to_all_values' AS feature FROM results_feature_testing WHERE "percentage_of_reoccurring_values_to_all_values" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'quantile__q_0.1' AS feature FROM results_feature_testing WHERE "quantile__q_0.1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'quantile__q_0.2' AS feature FROM results_feature_testing WHERE "quantile__q_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'quantile__q_0.3' AS feature FROM results_feature_testing WHERE "quantile__q_0.3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'quantile__q_0.4' AS feature FROM results_feature_testing WHERE "quantile__q_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'quantile__q_0.6' AS feature FROM results_feature_testing WHERE "quantile__q_0.6" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'quantile__q_0.7' AS feature FROM results_feature_testing WHERE "quantile__q_0.7" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'quantile__q_0.8' AS feature FROM results_feature_testing WHERE "quantile__q_0.8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'quantile__q_0.9' AS feature FROM results_feature_testing WHERE "quantile__q_0.9" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'range_count__max_1__min_-1' AS feature FROM results_feature_testing WHERE "range_count__max_1__min_-1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'ratio_value_number_to_time_series_length' AS feature FROM results_feature_testing WHERE "ratio_value_number_to_time_series_length" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'sample_entropy' AS feature FROM results_feature_testing WHERE "sample_entropy" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'skewness' AS feature FROM results_feature_testing WHERE "skewness" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'spkt_welch_density__coeff_2' AS feature FROM results_feature_testing WHERE "spkt_welch_density__coeff_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'spkt_welch_density__coeff_5' AS feature FROM results_feature_testing WHERE "spkt_welch_density__coeff_5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'spkt_welch_density__coeff_8' AS feature FROM results_feature_testing WHERE "spkt_welch_density__coeff_8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'standard_deviation' AS feature FROM results_feature_testing WHERE "standard_deviation" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'sum_of_reoccurring_data_points' AS feature FROM results_feature_testing WHERE "sum_of_reoccurring_data_points" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'sum_of_reoccurring_values' AS feature FROM results_feature_testing WHERE "sum_of_reoccurring_values" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'sum_values' AS feature FROM results_feature_testing WHERE "sum_values" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.0' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.05' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.05" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.1' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.15000000000000002' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.15000000000000002" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.2' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.25' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.25" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.30000000000000004' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.30000000000000004" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.35000000000000003' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.35000000000000003" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.4' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.4" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.45' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.45" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.5' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.5" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.55' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.55" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.6000000000000001' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.6000000000000001" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.65' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.65" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.7000000000000001' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.7000000000000001" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.75' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.75" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.8' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.8" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.8500000000000001' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.8500000000000001" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.9' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.9" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'symmetry_looking__r_0.9500000000000001' AS feature FROM results_feature_testing WHERE "symmetry_looking__r_0.9500000000000001" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'time_reversal_asymmetry_statistic__lag_1' AS feature FROM results_feature_testing WHERE "time_reversal_asymmetry_statistic__lag_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'time_reversal_asymmetry_statistic__lag_2' AS feature FROM results_feature_testing WHERE "time_reversal_asymmetry_statistic__lag_2" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'time_reversal_asymmetry_statistic__lag_3' AS feature FROM results_feature_testing WHERE "time_reversal_asymmetry_statistic__lag_3" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'value_count__value_-inf' AS feature FROM results_feature_testing WHERE "value_count__value_-inf" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'value_count__value_0' AS feature FROM results_feature_testing WHERE "value_count__value_0" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'value_count__value_1' AS feature FROM results_feature_testing WHERE "value_count__value_1" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'value_count__value_inf' AS feature FROM results_feature_testing WHERE "value_count__value_inf" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'value_count__value_nan' AS feature FROM results_feature_testing WHERE "value_count__value_nan" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'variance' AS feature FROM results_feature_testing WHERE "variance" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id UNION
SELECT AVG(accuracy) AS accuracy, source_device, target_device, source_dataset, target_dataset, scaled_independently, feature as sensor_stream_id, 'variance_larger_than_standard_deviation' AS feature FROM results_feature_testing WHERE "variance_larger_than_standard_deviation" > 0 GROUP BY source_device, target_device, source_dataset, target_dataset, scaled_independently, sensor_stream_id
) t
JOIN devices AS source_devices ON source_devices.id = t.source_device
JOIN devices AS target_devices ON target_devices.id = t.target_device
JOIN features ON features.id = t.sensor_stream_id
JOIN datasets AS source_datasets ON source_datasets.id = t.source_dataset
JOIN datasets AS target_datasets ON target_datasets.id = t.target_dataset
JOIN device_locations AS source_locations ON source_locations.device_id = t.source_device AND source_locations.dataset_id = t.source_dataset
JOIN device_locations AS target_locations ON target_locations.device_id = t.target_device AND target_locations.dataset_id = t.target_dataset;
